name: AniList readme workflow
on:
    schedule:
        # Every 30 minutes, between 01:00 PM and 03:59 AM
        - cron: "*/30 13-3 * * *"
    workflow_dispatch:

jobs:
    update-readme-with-anilist:
        name: Update this repo's README with latest AniList activites
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: AniList readme workflow
              uses: pxseu/anilist-readme@v1.4.2

              with:
                  user_id: 5790266
                  max_post_count: 10
                  commit_message: "تحديث • Anilist Activity"
                  timezone: "Europe/Berlin"
                  date_format: "{h}:{m} // {D} {MW}, {Y}"
