name: Update README
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.README_GH }}
        with:
          COMMIT_MSG: "تحديث • GitHub Activity"
          MAX_LINES: 10
          COMMIT_NAME: "オタ"
